window.Components = 'app.components'
angular.module('app', [
  'app.modules'
  'app.resources'
  'app.components'
  'app.filters'
  'app.services'
  'ngAnimate'
  'ngResource'
  'ngCookies'
  'ui.router'
  'ui.bootstrap'
  'ui.select2'
  'yaMap'
  'angularFileUpload'
])